### ISSUE TITLE
button builder broken

### ISSUE THREAD

**Issue by Slender4fun** [mProjectsCode/obsidian-meta-bind-plugin#433]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persists with all other plugins and themes disabled

### Plugin Version

1.2.1

### This Issue Occurs on

- [X] macOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.14
	Operating system: Darwin Kernel Version 22.6.0: Mon Apr 22 20:49:37 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_ARM64_T6000 22.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 1
		1: Meta Bind v1.2.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

if i add any otehr function than "input" or "command" the button-builder does not show the action added. if i first add one of the above, then an other (no visible change) and then delete the first object, only the title changes and shows the second added item. action context does not change ( so my title is now "open link" but the text below says "the text to input at the cursor")

<img width="536" alt="grafik" src="https://github.com/user-attachments/assets/a671995f-f59e-49eb-9210-e07f86c3d912">

### Steps to Reproduce

install newest plugin version. 
try to build a button

### Expected Behavior

shows growing list of actions under the "actions" heading in the button-builder

**Comment by mProjectsCode** [comment]
Can you check if this issue persists in version 1.2.2?

**Comment by Slender4fun** [comment]
if i "add action" for "open" noting happens. i can now also not add any other action. have to reopen the button configurator.

if i add "command" it appears normal. then i add "open", nothing happens. then i "move down" the first action. the scrollbar got longer just now. Above is now the title of "open a link" but no context under it. 

<img width="531" alt="grafik" src="https://github.com/user-attachments/assets/dbc5cedb-9e26-4af1-9cb5-c0c307a0c73e">

debuginfo:
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.14
	Operating system: Darwin Kernel Version 22.6.0: Mon Apr 22 20:49:37 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_ARM64_T6000 22.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Meta Bind v1.2.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by motion2082** [comment]
Seems to add the Open but you need to edit in source mode. If you try to add as a template it doesn't work at all

**Comment by motion2082** [comment]
![error](https://github.com/user-attachments/assets/862f9a6f-9d45-481e-8ef7-b6e463248b39)
![error2](https://github.com/user-attachments/assets/86189557-dcbe-4ca1-8cb8-e7e992dd580b)
![Uploading error3.png…]()

**Comment by motion2082** [comment]
Meta Bind v1.2.3

Meta Bind Button Builder

Error when Adding OPEN Action
![open-error](https://github.com/user-attachments/assets/861ba3b7-581e-4436-846a-a2b290bec24e)

**Comment by mProjectsCode** [comment]
This button builder is driving me insane :(

**Comment by mProjectsCode** [comment]
The last problem from @motion2082 screenshot should be fixed in 1.2.4

**Comment by motion2082** [comment]
Appreciate you pushing out 2 updates in the past week to try fix it. I was just using an older version but I edit buttons in source for broken Open Command and the broken Edit Template Button I don’t use. Can always open in data.json and edit there.


Outstanding issues I’m having:

1. The Button Template Builder Edit button feature is still broken in 1.2.4 by the looks.

2. Adding Open Command also still isn’t working

I will test on another Vault tomorrow as I have about 38 plugins in my Production Vault.

**Comment by mProjectsCode** [comment]
Oh, in 1.2.4 I fixed the issue new buttons, but I didn't account for "broken" buttons in the template buttons.

**Comment by mProjectsCode** [comment]
I just released a better fix in 1.2.5 that should work with existing templates and does not require any migrations.

**Comment by motion2082** [comment]
Thank you so much Moritz

Both the Template Editor and Open Feature in Button Builder are now fixed in 1.2.5 

I have an exciting project in the works related to your Plugin, will share it with you when it's completed
